### ISSUE TITLE
Work Sample TODO's

### ISSUE THREAD

**Issue by Lsmith2895** [Lsmith2895/Flexpa-Work-Sample#1]
- [ ] Read through API docs
- [ ] setup app with typescript, react, axios, tailwind
- [ ] Follow the [Flexpa Link](https://www.flexpa.com/docs/tools/link) guide to add Flexpa Link to a React frontend to start the authorization.
- [ ] [Exchange](https://www.flexpa.com/docs/tools/link#exchange-public-token-for-access-token) the public_token for an access_token in a backend to complete the authorization.
- [ ] Use the [Flexpa API](https://www.flexpa.com/docs/tools/api) with that access_token to request an [ExplanationOfBenefit](https://www.flexpa.com/docs/fhir-resources/explanation-of-benefit) resource from a payer test server (you can find test credentials in our [test mode guide](https://www.flexpa.com/docs/getting-started/test-mode)). (Make sure to opt-in to our [improved API experience](https://www.flexpa.com/docs/tools/api#improved-api-experience) with the X-Flexpa-Raw header.)
- [ ] Create a component to display some information from the ExplanationOfBenefit in the frontend.
- [ ] Publish your source to a public repository (e.g. on Github) and email the link to [hiring@flexpa.com](mailto:hiring@flexpa.com).
